### ISSUE TITLE
The configuration file does not exist.

### ISSUE THREAD

**Issue by nyilasviktor0625** [Open-Games-Community/BlizzCMS-Formorgar-Mines#1]

**Comment by Alexv45** [comment]
Hello,

Check the link in description download it directly from our forum, maybe the pull of github have made a mistake on one file.

**Comment by nyilasviktor0625** [comment]
ohh okey, but i havent got a permission to download :(

**Comment by nyilasviktor0625** [comment]
![kép](https://github.com/Open-Games-Community/BlizzCMS-Formorgar-Mines/assets/55741832/7ee3ce7b-a636-4ffc-bea0-c86f4b360a49)

**Comment by Alexv45** [comment]
> ![kép](https://user-images.githubusercontent.com/55741832/270111578-7ee3ce7b-a636-4ffc-bea0-c86f4b360a49.png)

You need create an account in order to download something from forum.
Today this CMS has been downloaded by 4 users.

Regards,
